In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [3]:
noOfInputs=5 #constant number of inputs
noOfLayers=2 #don't count the output layer as a layer
layerSizes=[2] #don't count the output layer
noOfOutputs=3 #constant number of outputs
initRandWeightMin=-1
initRandWeightMax=1
labels=np.zeros(10)
activationFunction= sigmoid #or np.tanh
lr = 0.001 # learning rate

In [4]:
def initWeights(layerSizes):
    noOfLayers=len(layerSizes)
    weights=[]
    weights.append(np.random.uniform(low=initRandWeightMin,high=initRandWeightMax,size=(noOfInputs,layerSizes[0])))
    for i,l in enumerate(layerSizes[:-1]):
        weights.append(np.random.uniform(low=initRandWeightMin,high=initRandWeightMax,size=(l,layerSizes[i+1]))) #weights between last layer and the final output neurons

    weights.append(np.random.uniform(low=initRandWeightMin,high=initRandWeightMax,size=(layerSizes[-1],noOfOutputs))) #weights between last layer and the final output neurons
    return weights

In [5]:
def initNeuronsOutput():
    neuronsOutput=[]
    neuronsOutput.append(np.random.random(noOfInputs))
    for l in layerSizes:
        neuronsOutput.append(np.random.random(l))
    neuronsOutput.append(np.random.random(noOfOutputs))
    return neuronsOutput

In [6]:
def initErrors():
    errors=[]
    for l in layerSizes:
        errors.append(np.random.random(l))
    errors.append(np.random.random(noOfOutputs))
    return errors

In [7]:
weights= initWeights(layerSizes)
weights

[array([[-0.56801382,  0.0017587 ],
        [-0.4175348 ,  0.99357617],
        [ 0.44549562, -0.87814079],
        [-0.81562292,  0.07291036],
        [-0.78219629,  0.31891885]]),
 array([[ 0.87091844, -0.61842101, -0.61685186],
        [ 0.53052636,  0.85191109, -0.47035332]])]

In [8]:
neuronsOutput=initNeuronsOutput()
neuronsOutput

[array([0.38942607, 0.72217315, 0.71766395, 0.31534315, 0.65187745]),
 array([0.77101391, 0.0851797 ]),
 array([0.32725532, 0.78412914, 0.74827546])]

In [9]:
errors=initErrors()
errors

[array([0.57273209, 0.34407674]), array([0.4377398 , 0.86415734, 0.09372852])]

- A 'layer' is a layer of neurons
- A 'connection' is the set of weights between two layers

In [10]:
def feedForward():
    for j,connection in enumerate(weights):
        for i in range(connection.shape[1]):
            neuronsOutput[j+1][i]=activationFunction(connection[:,i].dot(neuronsOutput[j])) #should we transpose or not

In [11]:
def finalError(label):
    return (label-neuronsOutput[-1])*neuronsOutput[-1]*(1-neuronsOutput[-1])

In [12]:
def backPropagation(label):
    for k in range(noOfOutputs):
        if(label==k):
            errors[-1][k]= (1-neuronsOutput[-1][k])*neuronsOutput[-1][k]*(1-neuronsOutput[-1][k])
        else:
            errors[-1][k]= (0-neuronsOutput[-1][k])*neuronsOutput[-1][k]*(1-neuronsOutput[-1][k])
    for j in range(len(weights)-1,-1,-1):
        for i in range(errors[j-1].shape[0]):
            errors[j-1][i]=(errors[j].T.dot(weights[j][i,:]))*(1-neuronsOutput[j-1][i]) #should we transpose or not

In [14]:
backPropagation(1)

I LOVE obfuscated code

In [ ]:
def updateWeights():
    for i,connection in enumerate(weights): #Loop over every connection between every two layers
        for j in range(connection.shape[1]): # loop over every layer's neurons
            for k in range(connection.shape[0]): # loop over all the incoming weights to this neuron
                weights[i][k,j]=weights[i][k,j]+lr*errors[i][j]*neuronsOutput[i][k]
                # Rule: weight=weight+lr*error*input

In [ ]:
updateWeights() # it works but the error is very small so the difference is small

In [36]:
weights

[array([[-0.56801116,  0.00180354],
        [-0.41752987,  0.99365932],
        [ 0.44550052, -0.87805816],
        [-0.81562077,  0.07294667],
        [-0.78219184,  0.3189939 ]]),
 array([[ 0.87091654, -0.61840244, -0.61687089],
        [ 0.53052615,  0.85191314, -0.47035542]])]

Don't take any function for granted, not showing errors doesn't neccessarly mean working correctly

In [ ]:
#TODO: add an option for the bias