In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [3]:
noOfInputs=2
noOfLayers=2 #don't count the output layer as a layer
layerSizes=[2] #don't count the output layer
noOfOutputs=1
initRandWeightMin=-1
initRandWeightMax=1
labels=np.zeros(10)
activationFunction= sigmoid #or np.tanh

In [4]:
def initWeights(layerSizes):
    noOfLayers=len(layerSizes)
    weights=[]
    weights.append(np.random.uniform(low=initRandWeightMin,high=initRandWeightMax,size=(noOfInputs,layerSizes[0])))
    for i,l in enumerate(layerSizes[:-1]):
        weights.append(np.random.uniform(low=initRandWeightMin,high=initRandWeightMax,size=(l,layerSizes[i+1]))) #weights between last layer and the final output neurons

    weights.append(np.random.uniform(low=initRandWeightMin,high=initRandWeightMax,size=(layerSizes[-1],noOfOutputs))) #weights between last layer and the final output neurons
    return weights

In [5]:
def initNeuronsOutput():
    neuronsOutput=[]
    neuronsOutput.append(np.random.random(noOfInputs))
    for l in layerSizes:
        neuronsOutput.append(np.random.random(l))
    neuronsOutput.append(np.random.random(noOfOutputs))
    return neuronsOutput

In [6]:
def initErrors():
    errors=[]
    for l in layerSizes:
        errors.append(np.random.random(l))
    errors.append(np.random.random(noOfOutputs))
    return errors

In [7]:
weights= initWeights(layerSizes)
weights

[array([[-0.34473866,  0.8482733 ],
        [ 0.86289741,  0.67044995]]),
 array([[ 0.19412427],
        [-0.68968343]])]

In [8]:
neuronsOutput=initNeuronsOutput()
neuronsOutput

[array([0.07309734, 0.00827292]),
 array([0.50022632, 0.19977644]),
 array([0.97346869])]

In [9]:
errors=initErrors()
errors

[array([0.55187291, 0.58855372]), array([0.84369106])]

- A 'layer' is a layer of neurons
- A 'connection' is the set of weights between two layers

In [10]:
def feedForward():
    for j,connection in enumerate(weights):
        for i in range(connection.shape[1]):
            neuronsOutput[j+1][i]=activationFunction(connection[:,i].dot(neuronsOutput[j]))

This notebook assumes that the number of output neurons is equal to 1

In [11]:
def finalError(label):
    return (-neuronsOutput[-1])*neuronsOutput[-1]*(1-neuronsOutput[-1])

In [12]:
weights

[array([[-0.34473866,  0.8482733 ],
        [ 0.86289741,  0.67044995]]),
 array([[ 0.19412427],
        [-0.68968343]])]

In [13]:
neuronsOutput

[array([0.07309734, 0.00827292]),
 array([0.50022632, 0.19977644]),
 array([0.97346869])]

In [14]:
errors

[array([0.55187291, 0.58855372]), array([0.84369106])]

In [21]:
def backPropagation(label):
    errors[-1]= finalError(label)
    for j in range(len(weights)-1,-1,-1):
        for i in range(weights[j].shape[0]):
            errors[j-1][i-1]
            errors[j]
            weights[j][i,:]
            errors[j-1][i-1]=errors[j].dot(weights[j][i,:])

In [22]:
backPropagation(1)

In [23]:
errors

[array([ 0.01734013, -0.0048807 ]), array([0.01169049])]